apiVersion: v1
kind: Service
metadata:
  name: nebius-personal-ai
spec:
  selector:
    app: nebius-personal-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP